parameters:
  name: '' # defaults for any parameters that aren't specified
  vmImage: ''
  scripts: []

jobs:
  - ${{ each script in parameters.scripts }}: # Each job
      - ${{ each pair in script }}:
          - job: ${{ format({0}{1}, parameters.name, pair.value.displayName) }}
            pool:
              vmImage: ${{ parameters.vmImage }}
            steps:
              - template: yarn-install.yml
            ${{ pair.key }}: ${{ pair.value }}
