variables:
  CI: 'true'
  PNPM_CACHE_FOLDER: $(Pipeline.Workspace)/.pnpm-store

jobs:
  - template: pipeline-jobs.yml
    parameters:
      name: Linux
      vmImage: 'ubuntu-latest'

  - template: pipeline-jobs.yml
    parameters:
      name: macOS
      vmImage: 'macOS-latest'

# What triggers a new build
trigger:
  - main
  - next
  - ci/*

# The branches which cause a PR to trigger a new build
pr:
  - main
  - next
