name: storybook

on:
  push:
    branches:
      - beta
  pull_request:
    types: [opened, synchronize]
    branches:
      - beta

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  deploy_docs:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: setup caching
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          # Uses node 14 to allow nullish coalescing in `.js` files
          node-version: 14

      - name: install and audit
        uses: ./support/actions/pnpm
        with:
          cache: ${{ env.PNPM_CACHE_FOLDER }}

      - name: build storybook
        run: pnpm storybook:build

      - name: deploy storybook
        uses: amondnet/vercel-action@v20
        with:
          working-directory: ./packages/storybook-react/storybook-static
          vercel-token: ${{ secrets.VERCEL_STORYBOOK_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_STORYBOOK_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_STORYBOOK_PROJECT_ID }}
          # deploy to production if the git reference is 'beta'.
          vercel-args: ${{ ((env.GITHUB_REF == 'beta') || '--prod') && '' }}
          # necessary for comment on pull request and commit.
          github-token: ${{ secrets.GITHUB_TOKEN }}
